#!/bin/ksh -f

# @(#) creotojt
# @(#) Copyright 2014 Siemens Product Lifecycle Management Software Inc.
# @(#) This script sets env variables and runs the INVENTOR to JT translator

if [ -z "${INVENTOR_JT_INSTALL}" ]; then
  echo "INVENTOR_JT_INSTALL environment variable is not set"
  echo "Please set this environment variable before running the translator"
  echo "Exiting..."
  exit 1
fi

APPNAME=${INVENTOR_JT_INSTALL}/jt_inventor

EAI_INSTALL=${INVENTOR_JT_INSTALL}
export EAI_INSTALL

LD_LIBRARY_PATH=${INVENTOR_JT_INSTALL}:${LD_LIBRARY_PATH}
export LD_LIBRARY_PATH

exec ${APPNAME} "-single_part" "$@" 
