#!/bin/ksh -f

# @(#) acistojt
# @(#) Copyright 2014 Siemens Product Lifecycle Management Software Inc.
# @(#) This script sets env variables and runs the ACIS to JT translator

if [ -z "${ACIS_JT_INSTALL}" ]; then
  echo "ACIS_JT_INSTALL environment variable is not set"
  echo "Please set this environment variable before running the translator"
  echo "Exiting..."
  exit 1
fi

APPNAME=${ACIS_JT_INSTALL}/jt_acis

EAI_INSTALL=${ACIS_JT_INSTALL}
export EAI_INSTALL

LD_LIBRARY_PATH=${ACIS_JT_INSTALL}:${LD_LIBRARY_PATH}
export LD_LIBRARY_PATH

exec ${APPNAME} "$@" 
